# Generated by Django 2.2.1 on 2019-05-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_user', models.CharField(blank=True, max_length=120, null=True, verbose_name='usuario o email')),
                ('password', models.CharField(blank=True, max_length=120, null=True, verbose_name='contraseña')),
                ('num_documento', models.CharField(blank=True, max_length=120, null=True, verbose_name='num_documento')),
                ('nombres', models.CharField(blank=True, max_length=120, null=True, verbose_name='nombres')),
                ('apellidos', models.CharField(blank=True, max_length=120, null=True, verbose_name='apellidos')),
                ('foto', models.ImageField(upload_to='fotos', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
