# Generated by Django 2.2.1 on 2019-05-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.FileField(null=True, upload_to='fotos', verbose_name='Foto'),
        ),
    ]
