# Generated by Django 2.2.1 on 2019-05-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190507_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
    ]
