# Generated by Django 2.2.1 on 2019-05-07 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de modificación')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('tipo_tablero', models.CharField(choices=[('PRIVADO', 'PRIVADO'), ('PUBLICO', 'PÚBLICO')], help_text='Si es público o privado', max_length=30, verbose_name='Tipo de tablero')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tablero_creado_por', to='users.User', verbose_name='Creado Por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tablero_modificado_por', to='users.User', verbose_name='Modificado Por')),
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tableros',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de modificación')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('aprobada', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='aprobada')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idea_creado_por', to='users.User', verbose_name='Creado Por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idea_modificado_por', to='users.User', verbose_name='Modificado Por')),
                ('tablero', models.ForeignKey(help_text='Tablero al que pertenece la idea', on_delete=django.db.models.deletion.PROTECT, to='tableros.Tablero', verbose_name='Tablero')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
            },
        ),
    ]
