# Generated by Django 2.2.1 on 2019-05-08 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_creado_por', to='users.User', verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_modificado_por', to='users.User', verbose_name='Modificado Por'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='tablero',
            field=models.ForeignKey(help_text='Tablero al que pertenece la idea', on_delete=django.db.models.deletion.CASCADE, to='tableros.Tablero', verbose_name='Tablero'),
        ),
    ]
