# Generated by Django 2.2.1 on 2019-05-08 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0002_auto_20190508_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_creado_por', to='users.User', verbose_name='Creado Por'),
        ),
    ]
