# Generated by Django 2.2.1 on 2019-05-08 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0003_auto_20190508_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_modificado_por', to='users.User', verbose_name='Modificado Por'),
        ),
    ]
